/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Modelo.UsuarioVO;
import Controlador.Controlador;
/**
 *
 * @author ET36
 */
public class PantallaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PantallaPrincipal
     * @param _ventanaPrincipal
     */
    public PantallaPrincipal(VentanaPrincipal _ventanaPrincipal) {
        ventanaPrincipal = _ventanaPrincipal;
        initComponents();
    }
    public PantallaPrincipal(VentanaPrincipal _ventanaPrincipal, Controlador _controlador) {
        ventanaPrincipal = _ventanaPrincipal;
        controlador = _controlador;
        initComponents();
    }
    public Controlador getControlador(){
        return controlador;
    }
     public void setControlador(Controlador _controlador){
        controlador = _controlador;
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelContrasena = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        textoUsuario = new javax.swing.JTextField();
        modoForms = new javax.swing.JLabel();
        esProfesor = new javax.swing.JCheckBox();
        labelUsuario = new javax.swing.JLabel();
        textoContrasenia = new javax.swing.JPasswordField();
        btnCambiar = new javax.swing.JButton();
        labelTitulo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelContrasena.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        labelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContrasena.setText("Contraseña");

        btnEnviar.setBackground(new java.awt.Color(51, 204, 255));
        btnEnviar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Registrarse");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        textoUsuario.setToolTipText("");
        textoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));
        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });

        modoForms.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        modoForms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modoForms.setText("REGISTRARSE");
        modoForms.setToolTipText("");
        modoForms.setAlignmentX(1.0F);
        modoForms.setAlignmentY(1.0F);
        modoForms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        esProfesor.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        esProfesor.setText("Profesor");
        esProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        esProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esProfesorActionPerformed(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("Nombre de usuario");

        textoContrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        textoContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseniaActionPerformed(evt);
            }
        });

        btnCambiar.setBackground(new java.awt.Color(153, 153, 153));
        btnCambiar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnCambiar.setText("Iniciar Sesión");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        labelTitulo1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        labelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo1.setText("JBrain");
        labelTitulo1.setToolTipText("JBrain");
        labelTitulo1.setAlignmentX(1.0F);
        labelTitulo1.setAlignmentY(1.0F);
        labelTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(esProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modoForms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoContrasenia)
                    .addComponent(btnCambiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addComponent(labelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(modoForms, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiar)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        if(btnEnviar.getText()== "Registrarse"){
            String usuario = textoUsuario.getText();
            String contrasenia = textoContrasenia.getText();
            String tipoUsuario;
            if (esProfesor.isSelected()){
                tipoUsuario = "Profesor";
            }else{
                tipoUsuario = "Alumno";
            }
            UsuarioVO usuarioVO = new UsuarioVO(usuario,contrasenia, tipoUsuario);
       
            controlador.registrarse(usuarioVO);
            
        }else if (btnEnviar.getText()== "Iniciar Sesión"){
            String usuario = textoUsuario.getText();
            String contrasenia = textoContrasenia.getText();
            controlador.iniciarSesion(usuario,contrasenia);
        }
        if(Controlador.usuarioIniciado != null){
            ventanaPrincipal.cerrarAbrirPanel(this, "MenuPrincipal");
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuarioActionPerformed

    private void esProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esProfesorActionPerformed

    private void textoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseniaActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        if(btnEnviar.getText()== "Registrarse"){
            esProfesor.setVisible(false);
            btnEnviar.setText("Iniciar Sesión");
            btnCambiar.setText("Registrarse");
            modoForms.setText("INICIAR SESIÓN");
        }
        else{
            btnEnviar.setText("Registrarse");
            esProfesor.setVisible(true);
            btnCambiar.setText("Iniciar Sesión");
            modoForms.setText("REGISTARSE");
        }
        
    }//GEN-LAST:event_btnCambiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JCheckBox esProfesor;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel modoForms;
    private javax.swing.JPasswordField textoContrasenia;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
    private VentanaPrincipal ventanaPrincipal;
    private Controlador controlador;

}
