/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.Controlador;
import Modelo.PreguntaVO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
/**
 *
 * @author Mati y Santi
 */
public class ResponderPreguntas extends javax.swing.JPanel {
    private ArrayList<PreguntaVO> preguntas;
    private ArrayList<String> respuestas;
    private int i;
    private int respuestasCorrectas;
    private double promedio;
    /**
     * Creates new form ResponderPreguntas
     */
    public ResponderPreguntas(VentanaPrincipal _ventanaPrincipal, Controlador _controlador) {
        ventanaPrincipal = _ventanaPrincipal;
        controlador = _controlador;
        
        i = 0;
        
         initComponents();
        
    }
    
    public void hacerPreguntas(ArrayList<PreguntaVO> _preguntas){
            if (i<preguntas.size()){
                respuestas = new ArrayList();
                respuestas.add(_preguntas.get(i).getOpcionCorrecta());
                respuestas.add(_preguntas.get(i).getOpcionIncorrecta1());
                respuestas.add(_preguntas.get(i).getOpcionIncorrecta2());
                respuestas.add(_preguntas.get(i).getOpcionIncorrecta3());
                Collections.shuffle(respuestas);
                pregunta.setText(_preguntas.get(i).getPregunta());
                respuesta1.setText(respuestas.get(0));
                respuesta2.setText(respuestas.get(1));
                respuesta3.setText(respuestas.get(2));
                respuesta4.setText(respuestas.get(3));   
            }else{
                promedio = respuestasCorrectas*10/preguntas.size();
                JOptionPane.showMessageDialog(null, "Ya terminó el formulario\n Usted acertó "+respuestasCorrectas+" de "+preguntas.size()+"\n Obtuvo un promedio de "+promedio);
                
                controlador.ingresarAlumnosala(promedio);
                Controlador.salaActual = null;
                ventanaPrincipal.cerrarAbrirPanel(this,"MenuPrincipal");
            }
    }
    public void cargarPreguntas(ArrayList<PreguntaVO> _preguntas){
        preguntas = _preguntas;
        hacerPreguntas(preguntas);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPreguntas = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        respuesta4 = new javax.swing.JButton();
        respuesta2 = new javax.swing.JButton();
        respuesta1 = new javax.swing.JButton();
        respuesta3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tituloPreguntas.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        tituloPreguntas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPreguntas.setText("Responde");
        tituloPreguntas.setToolTipText("");
        tituloPreguntas.setAlignmentX(1.0F);
        tituloPreguntas.setAlignmentY(1.0F);
        tituloPreguntas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pregunta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        respuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta4ActionPerformed(evt);
            }
        });

        respuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta2ActionPerformed(evt);
            }
        });

        respuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta1ActionPerformed(evt);
            }
        });

        respuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(respuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(respuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(pregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloPreguntas)
                .addGap(12, 12, 12)
                .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void respuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta4ActionPerformed
        // TODO add your handling code here:
       
        if (respuesta4.getText().contains(preguntas.get(i).getOpcionCorrecta())){
            respuestasCorrectas++;
        }
        i++;
        hacerPreguntas(preguntas);
    }//GEN-LAST:event_respuesta4ActionPerformed

    private void respuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta1ActionPerformed
        // TODO add your handling code here:
       
        if (respuesta1.getText().contains(preguntas.get(i).getOpcionCorrecta())){
            respuestasCorrectas++;
        }
         i++;
        hacerPreguntas(preguntas);
    }//GEN-LAST:event_respuesta1ActionPerformed

    private void respuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta2ActionPerformed
//        // TODO add your handling code here:

        if (respuesta2.getText().contains(preguntas.get(i).getOpcionCorrecta())){
            respuestasCorrectas++;
        }
         i++;
        hacerPreguntas(preguntas);
    }//GEN-LAST:event_respuesta2ActionPerformed

    private void respuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta3ActionPerformed
        // TODO add your handling code here:
        
        if (respuesta3.getText().contains(preguntas.get(i).getOpcionCorrecta())){
            respuestasCorrectas++;
        }
         i++;
        hacerPreguntas(preguntas);
    }//GEN-LAST:event_respuesta3ActionPerformed
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pregunta;
    private javax.swing.JButton respuesta1;
    private javax.swing.JButton respuesta2;
    private javax.swing.JButton respuesta3;
    private javax.swing.JButton respuesta4;
    private javax.swing.JLabel tituloPreguntas;
    // End of variables declaration//GEN-END:variables
    private Controlador controlador;
    private VentanaPrincipal ventanaPrincipal;
    private javax.swing.JButton boton;
}
