/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.Controlador;
/**
 *
 * @author ET36
 */
public class UnirseASala extends javax.swing.JPanel {

    /**
     * Creates new form UnirseASala
     */
    public UnirseASala(VentanaPrincipal ventana, Controlador controlador) {
        ventanaPrincipal = ventana;
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnirseSala = new javax.swing.JButton();
        modoForms = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        modoForms1 = new javax.swing.JLabel();
        textoSala = new javax.swing.JTextField();
        textoContraseniaSala = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        btnUnirseSala.setBackground(new java.awt.Color(51, 204, 255));
        btnUnirseSala.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnUnirseSala.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirseSala.setText("Unirse");
        btnUnirseSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseSalaActionPerformed(evt);
            }
        });

        modoForms.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        modoForms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modoForms.setText("Nombre sala:");
        modoForms.setToolTipText("");
        modoForms.setAlignmentX(1.0F);
        modoForms.setAlignmentY(1.0F);
        modoForms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelTitulo1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        labelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo1.setText("Salas");
        labelTitulo1.setToolTipText("");
        labelTitulo1.setAlignmentX(1.0F);
        labelTitulo1.setAlignmentY(1.0F);
        labelTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        modoForms1.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        modoForms1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modoForms1.setText("Contraseña:");
        modoForms1.setToolTipText("");
        modoForms1.setAlignmentX(1.0F);
        modoForms1.setAlignmentY(1.0F);
        modoForms1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textoSala.setToolTipText("");
        textoSala.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM));
        textoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSalaActionPerformed(evt);
            }
        });

        textoContraseniaSala.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        textoContraseniaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseniaSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoContraseniaSala, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(modoForms, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(btnUnirseSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modoForms1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoSala, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modoForms, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(modoForms1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContraseniaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnUnirseSala)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirseSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseSalaActionPerformed

        String nombreSala = textoSala.getText();
        String contraseniaSala = textoContraseniaSala.getText();
        controlador.unirseASala(nombreSala,contraseniaSala);
        if(Controlador.salaActual != null){
            
            ventanaPrincipal.cerrarAbrirPanel(this, "ResponderPreguntas");
            controlador.obtenerPreguntas(Controlador.salaActual.getIdSala());
        }
        

    }//GEN-LAST:event_btnUnirseSalaActionPerformed

    private void textoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSalaActionPerformed

    private void textoContraseniaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseniaSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseniaSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnirseSala;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel modoForms;
    private javax.swing.JLabel modoForms1;
    private javax.swing.JPasswordField textoContraseniaSala;
    private javax.swing.JTextField textoSala;
    // End of variables declaration//GEN-END:variables
    private VentanaPrincipal ventanaPrincipal;
    private Controlador controlador;


}
