/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.Controlador;
import java.awt.*;
import javax.swing.JPanel;

/**
 *
 * @author ET36
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Controlador controlador;
    private JPanel panelAbrir;
   
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initJPanel();
        
    }
    public Controlador getControlador(){
        return controlador;
    }
     public void setControlador(Controlador _controlador){
        controlador = _controlador;
    }   
    public PantallaPrincipal getPantallaPrincipal(){
        return pantallaPrincipal;
    }
     public void setPantallaPrincipal(PantallaPrincipal _pantallaPrincipal){
        pantallaPrincipal = _pantallaPrincipal;
    }  
    
    public void cerrarAbrirPanel(JPanel cerrar, String abrir){
        panelAbrir = pantallaPrincipal;
        cerrar.setVisible(false);
        remove(cerrar);
        if(abrir == "CrearFormulario"){
            panelAbrir = new CrearFormulario(this);
        }
        else if(abrir == "CrearSala"){
            panelAbrir = new CrearSala(this);        
        }
        else if(abrir == "UnirseASala"){
            panelAbrir = new UnirseASala(this, controlador);        
        }
        else if(abrir == "MenuPrincipal"){
            panelAbrir = new MenuPrincipal(this, controlador);        
        }
        else if(abrir == "PantallaPrincipal"){
            panelAbrir = new PantallaPrincipal(this,controlador);
        }
        else if(abrir == "ResponderPreguntas"){
            panelAbrir = new ResponderPreguntas(this,controlador);  
            this.setSize(600,500);
            controlador.setResponderPreguntas(panelAbrir);
        }
        else if(abrir == "EstadisticasAlumnos"){
            
            panelAbrir = new EstadisticasAlumnos(this,controlador);
            controlador.setEstadisticasAlumnos(panelAbrir);
        }
        
        add(panelAbrir);
        
        panelAbrir.setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initJPanel(){
        pantallaPrincipal = new PantallaPrincipal(this);
        setLayout(new BorderLayout());
        add(pantallaPrincipal, BorderLayout.CENTER);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
    }
    public void setPanelAbrir(JPanel panelAbrir) {
	this.panelAbrir = panelAbrir;
    }
    public JPanel getPanelAbrir() {
	return panelAbrir;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private MenuPrincipal menuPrincipal;
    private PantallaPrincipal pantallaPrincipal;
    private CrearSala crearSala;
    private CrearFormulario crearFormulario;
}
